variables:
  GIT_STRATEGY: clone

job: 
  stage: test
  script: 
    - mkdir -p data/diaspora/diaspora
    - cd docker
    - docker-compose run diaspora setup
    - docker-compose run diaspora init-db
