variables:
  GIT_STRATEGY: clone

job: 
  stage: test
  script: 
    - rm -rf data/diaspora
    - mkdir -p data/diaspora
    - chmod -R 777 .
    - cd docker
    - export HOST_UID=$(uid -u)
    - docker-compose build
    - docker-compose run diaspora setup
    - cp diaspora/test/* ../data/diaspora/diaspora/config
    - docker-compose run diaspora bundle
    - docker-compose run diaspora init-db

after_script:
  - cd docker
  - docker-compose kill
  - docker-compose rm -vf
