image: docker

stages:
- build
- deploy 

variables:
  IMAGE_LABEL: 'koehn/diaspora'
  IMAGE_TAG: 'latest'
  GIT_URL: 'https://github.com/diaspora/diaspora.git'
  GIT_BRANCH: 'master'

build-image:
  stage: build
  script:
  - "docker build -t $IMAGE_LABEL:$IMAGE_TAG --build-arg GIT_URL=${GIT_URL} --build-arg GIT_BRANCH=${GIT_BRANCH} ."

deploy-to-docker-hub:
  stage: deploy
  script:
  - 'docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"'
  - 'docker push $IMAGE_LABEL:$IMAGE_TAG'
