variables:
  GIT_STRATEGY: clone

job:
  stage: test
  script:
    - bin/init
    - cp docker/diaspora/test/* data/diaspora/diaspora/config
    - bin/bundle
    - bin/init-db
    - bin/backup

after_script:
  - cd docker
  - docker-compose kill
  - docker-compose rm -vf
  - rm -rf data/diaspora
