variables:
  GIT_STRATEGY: clone

job: 
  stage: test
  script: 
    - mkdir -p data/diaspora/diaspora
    - chmod -R 777 .
    - cd docker
    - docker-compose build --force-rm --no-cache
    - docker-compose run diaspora setup
    - docker-compose run diaspora bundle
    - docker-compose run diaspora init-db

after_script:
  - cd docker
  - docker-compose kill
  - docker-compose rm -vf
