version: '2'
services:
  httpd:
    build: ./httpd
    read_only: true
    links:
    - diaspora
    - camo
    ports:
    - '33060:80'
    restart: always
    volumes:
    - ./logs/httpd:/usr/local/apache2/logs
    - ./diaspora-local:/home/diaspora/diaspora:ro

  diaspora:
    build: 
      context: diaspora
      args:
      - GIT_URL=https://github.com/diaspora/diaspora.git
    links:
      - postgres
      - redis
    volumes:
      - ./diaspora-local:/home/diaspora/diaspora
      - ./logs/diaspora:/home/diaspora/diaspora/logs
    working_dir: /home/diaspora
    user: diaspora
    command: ./startup.sh
    ports:
      - '3000:3000'
    restart: always

  postgres:
    read_only: true
    mem_limit: 8G
    image: postgres:9.6
    tmpfs:
    - /tmp
    environment:
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_DB=diaspora_production
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres-run:/var/run/postgresql
      - ./postgres:/docker-entrypoint-initdb.d
      - ./backups/postgres:/backups
    restart: always

  redis:
    image: redis:latest
    mem_limit: 384M
    read_only: true
    tmpfs:
    - /tmp
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    restart: always

volumes:
  postgres:
  postgres-run:
  redis:
