version: '2'
services:
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=diaspora
      - POSTGRES_PASSWORD=diaspora
      - POSTGRES_DB=diaspora_production
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    privileged: true

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - redis:/data

  diaspora:
    build: diaspora
    links:
      - postgres
      - redis
    volumes:
      - ../data/diaspora:/home/diaspora/
      - ../data/backups:/backups
    ports:
      - "3000:3000"
    working_dir: /home/diaspora
    privileged: true
    command: run
    environment:
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}

volumes:
  postgres:
  redis:
