version: '2'
services:

  diaspora:
    build: 
      context: diaspora
      args:
      - GIT_URL=https://github.com/diaspora/diaspora.git
    links:
      - postgres
      - redis
    volumes:
      - diaspora-images:/home/diaspora/diaspora/public/uploads/images
    working_dir: /home/diaspora
    user: diaspora
    command: ./startup.sh
    ports:
      - '3000:3000'
    restart: always

  postgres:
    read_only: true
    mem_limit: 8G
    image: postgres:10.1-alpine
    tmpfs:
    - /tmp
    environment:
      - POSTGRES_USER=diaspora
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_DB=diaspora_production
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres-run:/var/run/postgresql
      - ./postgres:/docker-entrypoint-initdb.d
      - ./backups/postgres:/backups
    restart: always

  redis:
    image: redis:latest
    mem_limit: 384M
    read_only: true
    tmpfs:
    - /tmp
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    restart: always

volumes:
  diaspora-images:
  postgres:
  postgres-run:
  redis:
